[package]
name = "pibs"
version = "0.1.1"
authors = ["Maximilian Stahlberg"]
edition = "2024"
rust-version = "1.88"
description = "A primitive integer bitset for high-performance combinatorics"
documentation = "https://docs.rs/pibs"
readme = "README.md"
repository = "https://github.com/pibs-rs/pibs"
license = "MIT OR Apache-2.0"
keywords = ["bitset", "performance", "combinatorics", "math", "no_std"]
categories = ["algorithms", "data-structures", "mathematics", "no-std::no-alloc"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["alloc"]
alloc = []
serde = ["dep:serde"]

[dependencies]
num-traits = { version = "0.2.19", default-features = false }
serde = { version = "1.0.229", default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
bnum = { version = "0.14.4", default-features = false, features = ["numtraits"] }
criterion = "0.8.2"
itertools = "0.15.0"

[[bench]]
name = "criterion"
harness = false
